'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Student_Management_System.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Add_User_Male_96px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Add User Male_96px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Automation_96px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Automation_96px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Change_User_96px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Change User_96px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Conference_96px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Conference_96px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Delete_50px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete_50px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Denied_96px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Denied_96px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Find_User_Male_96px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Find User Male_96px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ID_Verified_96px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ID Verified_96px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Reading_100px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reading_100px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Shutdown_96px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Shutdown_96px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Student_Male_96px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Student Male_96px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Support_96px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Support_96px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Team_96px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Team_96px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Trash_Can_96px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Trash Can_96px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property User_Engagement_Male_96px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User Engagement Male_96px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property User_Groups_96px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User Groups_96px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Workspace_96px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Workspace_96px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
